@startuml
interface IProduct{
+ setColor():Object
}

class ProductA{
  + <<Implement>> setColor():Object
}

class ProductB{
  + <<Implement>> setColor():Object
}

class ProductC{
  + <<Implement>> setColor():Object
}

class Factory{
  + createProduct():IProduct
}

Factory --|> ProductA
Factory --|> ProductB
Factory --|> ProductC

ProductA ..> IProduct
ProductB ..> IProduct
ProductC ..> IProduct


@enduml
